[package]
name = "Multisend"
version = "0.0.0"

[addresses]
multisend = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "devnet"